// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Leaf } from "./Leaf";

export interface Node { name: string, path: string, children: Array<Node>, leafs: Array<Leaf>, }